package config

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"syscall"
)

func DataDir() (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", fmt.Errorf("resolve home: %w", err)
	}
	return filepath.Join(home, ".env-switcher"), nil
}

func SettingsPath() (string, error) {
	dir, err := DataDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(dir, "settings.yaml"), nil
}

// CurrentEnvPath is the fixed location the installed shell wrapper sources after every
// invocation. It holds the shell transaction generated by the most recent successful switch.
func CurrentEnvPath() (string, error) {
	dir, err := DataDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(dir, "current-env"), nil
}

// ExecutablePath is the fixed location the installed copy of the CLI lives at, regardless of
// shell. Both `install` and the self-install-on-first-run path resolve it from here.
func ExecutablePath() (string, error) {
	dir, err := DataDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(dir, "bin", "env-switcher"), nil
}

func ExpandHome(path string) (string, error) {
	if path == "~" || strings.HasPrefix(path, "~/") {
		home, err := os.UserHomeDir()
		if err != nil {
			return "", err
		}
		if path == "~" {
			return home, nil
		}
		return filepath.Join(home, path[2:]), nil
	}
	if strings.HasPrefix(path, "~") {
		return "", fmt.Errorf("only ~/ home expansion is supported")
	}
	return path, nil
}

func EnsurePrivate(path string, directory bool) error {
	info, err := os.Lstat(path)
	if err != nil {
		return err
	}
	if directory != info.IsDir() {
		return fmt.Errorf("unexpected file type for %s", path)
	}
	if info.Mode()&os.ModeSymlink != 0 {
		return fmt.Errorf("symbolic links are not accepted for %s", path)
	}
	if info.Mode().Perm()&0o077 != 0 {
		return fmt.Errorf("unsafe permissions on %s: require user-only access", path)
	}
	if stat, ok := info.Sys().(*syscall.Stat_t); ok && stat.Uid != uint32(os.Geteuid()) {
		return fmt.Errorf("unsafe ownership on %s: current user must own it", path)
	}
	return nil
}
